
namespace wServer.networking.packets
{
    public enum PacketId : byte
    {
        FAILURE = 0,
        CREATE_SUCCESS = 31,
        CREATE = 36,
        PLAYERSHOOT = 38,
        MOVE = 7,
        PLAYERTEXT = 69,
        TEXT = 25,
        SERVERPLAYERSHOOT = 13,
        DAMAGE = 47,
        UPDATE = 26,
        UPDATEACK = 11,
        NOTIFICATION = 63,
        NEWTICK = 62,
        INVSWAP = 65,
        USEITEM = 30,
        SHOWEFFECT = 56,
        HELLO = 17,
        GOTO = 52,
        INVDROP = 35,
        INVRESULT = 4,
        RECONNECT = 39,
        PING = 6,
        PONG = 16,
        MAPINFO = 60,
        LOAD = 45,
        PIC = 28,
        SETCONDITION = 10,
        TELEPORT = 49,
        USEPORTAL = 3,
        DEATH = 41,
        BUY = 50,
        BUYRESULT = 27,
        AOE = 68,
        GROUNDDAMAGE = 64,
        PLAYERHIT = 24,
        ENEMYHIT = 76,
        AOEACK = 59,
        SHOOTACK = 22,
        OTHERHIT = 66,
        SQUAREHIT = 51,
        GOTOACK = 14,
        EDITACCOUNTLIST = 53,
        ACCOUNTLIST = 46,
        QUESTOBJID = 34,
        CHOOSENAME = 33,
        NAMERESULT = 20,
        CREATEGUILD = 15,
        GUILDRESULT = 58,
        GUILDREMOVE = 78,
        GUILDINVITE = 8,
        ALLYSHOOT = 74,
        ENEMYSHOOT = 19,
        REQUESTTRADE = 21,
        TRADEREQUESTED = 61,
        TRADESTART = 67,
        CHANGETRADE = 37,
        TRADECHANGED = 23,
        ACCEPTTRADE = 57,
        CANCELTRADE = 1,
        TRADEDONE = 12,
        TRADEACCEPTED = 18,
        CLIENTSTAT = 75,
        CHECKCREDITS = 48,
        ESCAPE = 42,
        FILE = 55,
        INVITEDTOGUILD = 77,
        JOINGUILD = 5,
        CHANGEGUILDRANK = 40,
        PLAYSOUND = 44,
        GLOBAL_NOTIFICATION = 9,
        RESKIN = 79
    }
}
